### ISSUE TITLE
make server遇错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [yueyoum/make-proxy#5]
hi.

root@AR:~/make-proxy# ls
ChangeLog	       include	  server		 start_server.sh
client		       LICENSE	  server.config		 utils
client.config.example  Makefile   server.config.example
erl_crash.dump	       README.md  start_client.sh
root@AR:~/make-proxy# make server
cd server && ./rebar compile
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,enoent}},
                                [{rebar_utils,otp_release1,1,
                                  [{file,"src/rebar_utils.erl"},{line,416}]},
                                 {rebar_utils,get_arch,0,
                                  [{file,"src/rebar_utils.erl"},{line,95}]},
                                 {rebar_port_compiler,default_env,0,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,597}]},
                                 {rebar_port_compiler,setup_env,2,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,182}]},
                                 {rebar_core,'-setup_envs/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,523}]},
                                 {lists,foldl,3,
                                  [{file,"lists.erl"},{line,1261}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,294}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,259}]}]}}
make: *** [server] 错误 1
root@AR:~/make-proxy#

谢谢回复

**Comment by yueyoum** [comment]
看看你的 otp 版本是多少？ 
尽量用最新的

**Comment by luckypoem** [comment]
hi.

root@AR:~# erl --version
Erlang/OTP 17 [erts-6.1] [source] [smp:24:2] [async-threads:10] [hipe] [kernel-poll:false]

otp 版本是17,太低了吗？

**Comment by yueyoum** [comment]
要不手动操作一次看看

1. cd server 进入server目录
2. 执行 ./rebar co

看看什么情况？

这个错误确实奇怪， 我还没遇到过

**Comment by luckypoem** [comment]
hi.

root@AR:~/make-proxy/server# ls
rebar  rebar.config  src
root@AR:~/make-proxy/server# ./rebar compile
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,enoent}},
                                [{rebar_utils,otp_release1,1,
                                  [{file,"src/rebar_utils.erl"},{line,416}]},
                                 {rebar_utils,get_arch,0,
                                  [{file,"src/rebar_utils.erl"},{line,95}]},
                                 {rebar_port_compiler,default_env,0,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,597}]},
                                 {rebar_port_compiler,setup_env,2,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,182}]},
                                 {rebar_core,'-setup_envs/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,523}]},
                                 {lists,foldl,3,
                                  [{file,"lists.erl"},{line,1261}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,294}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,259}]}]}}
root@AR:~/make-proxy/server#
错误是一样的。
 
是否跟我自己安装的rebar有冲突所致？
root@AR:~/make-proxy/server# which rebar
/root/rebar//rebar
root@AR:~/make-proxy/server# ls ~/rebar/
appveyor.yml  bootstrap.bat    ebin	inttest  Makefile	 priv	    rebar	  rebar.config.sample  RELEASE-NOTES.md  test
bootstrap     CONTRIBUTING.md  include	LICENSE  pr2relnotes.py  README.md  rebar.config  rebar.config.script  src		 THANKS
root@AR:~/make-proxy/server#

**Comment by yueyoum** [comment]
不清楚啊， 我从 otp 16, 17, 18 版本都试过了， 都没问题

而且 makefile 调用的 仓库里的 rebar ，和系统 rebar 没关系

**Comment by luckypoem** [comment]
hi.
我知道原因了。就是你这程序里自带的rebar可执行文件有问题。我把它删除了。
root@AR:~/make-proxy/server# ls
rebar rebar.config src
root@AR:~/make-proxy/server# rm rebar
root@AR:~/make-proxy/server# ls
rebar.config src
root@AR:~/make-proxy/server# rebar compile
这样，输出的结果里没有错误。

在客户机器里，也是类似做法：
yudeMacBook-Air:make-proxy brite$ ls
ChangeLog		client.config		start_client.sh
LICENSE			client.config.example	start_server.sh
Makefile		include			utils
README.md		server
client			server.config.example
yudeMacBook-Air:make-proxy brite$ cd client
yudeMacBook-Air:client brite$ ls
rebar		rebar.config	src
yudeMacBook-Air:client brite$ rm rebar
yudeMacBook-Air:client brite$ ls
rebar.config	src
yudeMacBook-Air:client brite$ rebar compile
==> client (compile)
Compiled src/mpc_socks5_sup.erl
Compiled src/mpc_sup.erl
Compiled src/mpc_socks5_child.erl
Compiled src/mpc_http_sup.erl
Compiled src/mpc_app.erl
Compiled src/make_proxy_client.erl
Compiled ../utils/mp_crypto.erl
Compiled src/mpc_http_child.erl
yudeMacBook-Air:client brite$

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:make-proxy brite$ ls
ChangeLog		client.config		start_client.sh
LICENSE			client.config.example	start_server.sh
Makefile		include			utils
README.md		server
client			server.config.example
yudeMacBook-Air:make-proxy brite$ ./start_client.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
yudeMacBook-Air:make-proxy brite$ cat start_client.sh
#! /bin/bash

SELF=`readlink -f "$0"`
WORKDIR=`dirname "$SELF"`

cd "$WORKDIR"


running=`ps -ef | grep make_proxy_client | wc -l`
if [[ running -ge 2 ]]
then
    echo "alreay running"
    exit -1
else
    erl -pa client/ebin -config client +K true -s make_proxy_client start -detached
fi

exit 0

yudeMacBook-Air:make-proxy brite$ erl -pa client/ebin -config client +K true -s make_proxy_client start -detached
yudeMacBook-Air:make-proxy brite$

不过我还是翻墙失败，不知为何？

**Comment by luckypoem** [comment]
hi.

服务器端正常运行：
root@AR:~/make-proxy# ps aux|grep make_proxy_server
root     30695  0.0  2.0 378652 16284 ?        Sl   18:44   0:00 /root/.tools/otp_src_17.1/bin/i686-pc-linux-gnu/beam.smp -K true -- -root /root/.tools/otp_src_17.1 -progname erl -- -home /root -- -pa server/ebin -config server -s make_proxy_server start -noshell -noinput
root     30908  0.0  0.1   3584   820 pts/2    S+   20:21   0:00 grep make_proxy_server
root@AR:~/make-proxy# ls
ChangeLog	       include	 README.md	server.config.example  utils
client		       LICENSE	 server		start_client.sh
client.config.example  Makefile  server.config	start_server.sh
root@AR:~/make-proxy# cat server.config
[
{
    sasl,
    [
        {sasl_error_logger, {file, "server.log"}}
    ]
},
{
    make_proxy_server,
    [
        {port, 7071},
        {key, "xyz"}
    ]    
}
].
root@AR:~/make-proxy#

客户端也运行正常：(见上段内容）
yudeMacBook-Air:make-proxy yuming$ ls
ChangeLog		client.config		start_client.sh
LICENSE			client.config.example	start_server.sh
Makefile		include			utils
README.md		server
client			server.config.example
yudeMacBook-Air:make-proxy yuming$ cat client.config
[
{
    make_proxy_client,
    [
        {remote_addr, "my_vps_ip"},
        {remote_port, 7071},
        {local_socks5_port, 6060},
        {local_http_port, 6161},
        {key, "xyz"}
    ]    
}
].
yudeMacBook-Air:make-proxy yuming$

不知问题何在？

**Comment by yueyoum** [comment]
注意 readme 里的说明， key 必须是 16字节
也就是 得是一个 包含16个 char 的字符串

比如把 key 设置成 "1234567890abcdef" 这样的

**Comment by luckypoem** [comment]
hi.

不错。翻墙成功。建议还是把你自带的rebar可执行文件删除。在readme里面说明：用户需自行安装rebar

**Comment by yueyoum** [comment]
没确定是否是 仓库里的 rebar 导致的问题
因为我在本机 OTP 16 17 18 都没问题
linux 32位 64位也试过了

mac os 也试过了， 都是没问题。

所以我不清楚你那里到底是怎么了。。。
