### ISSUE TITLE
readlink on Mac issue

### ISSUE THREAD

**Issue by dongyuwei** [yueyoum/make-proxy#7]
```
sh start_client.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

I just deleted the  `readlink` related code in `start_client.sh`,  and it works on Mac 10.11.6 (15G31) as expected.

**Comment by yueyoum** [comment]
Yes. tool sets in Mac and Linux are not same. 
I will fix this problom with the next update. 
may be in few weeks.
