### ISSUE TITLE
server进程启动失败，erlang crashed

### ISSUE THREAD

**Issue by dongyuwei** [yueyoum/make-proxy#8]
With the latest code (commit `7f52591b9066cec57a1a8e701f6b3e9ed4f8f0ea`) , after compile successfully and run the `./start_server.sh`, the erlang crashed (system is `Mac 10.12.2`).

This is the `erl_crash.dump` log:
https://gist.github.com/dongyuwei/48a1703475cd7696860b89103f274572

When switch to the old commit `1f423f2b919696d5bbea110dd560ae5c6c398459`, it works.

**Comment by yueyoum** [comment]
不好意思，最近没上github。

我这里 ubuntu 测试没有问题。
你用的是 rebar3 吗？

是不是 mac 下rebar3 生成的目录和 Linux 不一样？

start_server.sh 脚本内容不一样：https://github.com/yueyoum/make-proxy/compare/1f42...master#diff-8dd7624b209245abdf5d84f4ebdd9a2b

1f 那个commit 还用的是 rebar
后面就改到用 rebar3 了

**Comment by dongyuwei** [comment]
ubuntu没有问题，是Mac  10.12.2上的问题。有空我再重新验证一下。
